### ISSUE TITLE
Deformation problem

### ISSUE THREAD

**Issue by a10954** [GiovanniTRA/transmatching#2]
Thanks for your excellent work and nice code!

I have downloaded the code and datasets, and tested it one the samples you gave. I see good results in your paper, but the results I came up with are not so good. I learned that this is to find the corresponding 3D position for each point of the source on the surface of the target, but the result does not appear to be on the surface of the target. The test here should not be a problem, as it is very close to the results in Table 2 of your paper. How should I do to get a better result? 

Thanks!

![image](https://user-images.githubusercontent.com/20322557/159196787-39e7933f-8314-47e6-abfb-3ac105229b16.png)

**Comment by GiovanniTRA** [comment]
Hi 邓奇-san.

Thanks for your interest in our project :)

What sample are you using for this visualization? I have tried running a few and the results seem slightly better (the head is less squashed).
 To get an idea of how results should look like you can see figure 13 of the arxiv version of the paper (the one linked in the repo). 

In the meanwhile, to improve results you can use the **refinement** procedure described in the last paragraph of section 4 of the paper. 
You can find the function "refine" under transmatching/utils/refine.py, mind that it is untested as per this version of the repo, so please let me know if you have any trouble using it. I might create a script to show its use in the following weeks.

Let me know if I can provide further assistance, 

Best, Gio

**Comment by a10954** [comment]
Thanks for the thorough explanation!

I tried the trained model you uploaded and it looks slightly better, but there is a bit of a big loss in training output and the alignment results slowly get worse after training. I think it's related to generalization, I will look at the code related to refinement for better results later.

Thanks!

**Comment by GiovanniTRA** [comment]
The high loss in training might be due to the fact that it is the euclidean loss (not squared though) summed over all datapoints in the epoch, so it is not on a comparable scale. 
Regarding the restarting of the training, in my experience it might cause some instabilities if you run it for just a couple epochs, but it should stabilize after a while.

**Comment by a10954** [comment]
I know the loss is summed over all data points in the epoch and is affected by dropout, but the float range would not be very large, so maybe it would be a good idea to train further on the trained model you uploaded  :)

Thanks for your answer!
